---
title: "west_ham_scraping"
author: "Max Cheatle"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup}

library(tidyverse)
library(rvest)
library(janitor)
library(RColorBrewer)
library(robotstxt)
library(dplyr)
library(scales)
library(lubridate)
library(caTools)
library(caret)

combined_fixtures <- read.csv("data/combined_fixtures.csv")
combined_shooting <- read.csv("data/combined_shooting.csv")
combined_passing <- read.csv("data/combined_passing.csv")
combined_poss <- read.csv("data/combined_poss.csv")

```


```{r fixtures}

library(httr)
paths_allowed("https://fbref.com")

scrape_fixtures <- function(url) {
  fixture_list <- url %>%
    read_html()
  
  fixtures <- data.frame(
    fixture_list %>%
      html_elements("#matchlogs_for") %>%
      html_table()
  ) %>% 
    janitor::clean_names() %>% 
    filter(comp == "Premier League") %>% 
    mutate(gf = as.character(gf),
           ga = as.character(ga))
  
  return(fixtures)
}

fixture_urls <- c(
  "https://fbref.com/en/squads/7c21e445/2017-2018/West-Ham-United-Stats#all_matchlogs",
  "https://fbref.com/en/squads/7c21e445/2018-2019/West-Ham-United-Stats#all_matchlogs",
  "https://fbref.com/en/squads/7c21e445/2019-2020/West-Ham-United-Stats#all_matchlogs",
  "https://fbref.com/en/squads/7c21e445/2020-2021/West-Ham-United-Stats#all_matchlogs",
  "https://fbref.com/en/squads/7c21e445/2021-2022/West-Ham-United-Stats#all_matchlogs",
  "https://fbref.com/en/squads/7c21e445/2022-2023/West-Ham-United-Stats#all_matchlogs"
)

all_fixtures <- list()

for (url in fixture_urls) {
  poss <- scrape_fixtures(url)
  all_fixtures[[url]] <- poss
  Sys.sleep(5)
}

combined_fixtures <- bind_rows(all_fixtures)

view(combined_fixtures)

```

```{r shooting}

scrape_shooting <- function(url) {
  shooting_list <- url %>%
    read_html()
  
  shooting <- data.frame(
    shooting_list %>%
      html_elements("#matchlogs_for") %>%
      html_table()
  ) %>% 
    janitor::clean_names()
  
  return(shooting)
}

shooting_urls <- c(
  "https://fbref.com/en/squads/7c21e445/2017-2018/matchlogs/all_comps/shooting/West-Ham-United-Match-Logs-All-Competitions",
  "https://fbref.com/en/squads/7c21e445/2018-2019/matchlogs/all_comps/shooting/West-Ham-United-Match-Logs-All-Competitions",
  "https://fbref.com/en/squads/7c21e445/2019-2020/matchlogs/all_comps/shooting/West-Ham-United-Match-Logs-All-Competitions",
  "https://fbref.com/en/squads/7c21e445/2020-2021/matchlogs/all_comps/shooting/West-Ham-United-Match-Logs-All-Competitions",
  "https://fbref.com/en/squads/7c21e445/2021-2022/matchlogs/all_comps/shooting/West-Ham-United-Match-Logs-All-Competitions",
  "https://fbref.com/en/squads/7c21e445/2022-2023/matchlogs/all_comps/shooting/West-Ham-United-Match-Logs-All-Competitions"
)

all_shooting <- list()

for (url in shooting_urls) {
  shooting <- scrape_shooting(url)
  all_shooting[[url]] <- shooting
  Sys.sleep(5)
}

combined_shooting <- bind_rows(all_shooting)

view(combined_shooting)

# Get the first row of the combined_shooting data frame
new_column_names <- as.character(combined_shooting[1, ])

# Set the new column names
colnames(combined_shooting) <- new_column_names

# Remove the first row from the combined_shooting data frame
combined_shooting <- combined_shooting[-1, ] %>% 
  janitor::clean_names() %>% 
  filter(comp == "Premier League") %>% 
  select(date:match_report)

view(combined_shooting)

```

```{r passing}

scrape_passing <- function(url) {
  passing_list <- url %>%
    read_html()
  
  passing <- data.frame(
    passing_list %>%
      html_elements("#matchlogs_for") %>%
      html_table()
  ) %>% 
    janitor::clean_names()
  
  return(passing)
}

passing_urls <- c(
  "https://fbref.com/en/squads/7c21e445/2017-2018/matchlogs/all_comps/passing/West-Ham-United-Match-Logs-All-Competitions",
  "https://fbref.com/en/squads/7c21e445/2018-2019/matchlogs/all_comps/passing/West-Ham-United-Match-Logs-All-Competitions",
  "https://fbref.com/en/squads/7c21e445/2019-2020/matchlogs/all_comps/passing/West-Ham-United-Match-Logs-All-Competitions",
  "https://fbref.com/en/squads/7c21e445/2020-2021/matchlogs/all_comps/passing/West-Ham-United-Match-Logs-All-Competitions",
  "https://fbref.com/en/squads/7c21e445/2021-2022/matchlogs/all_comps/passing/West-Ham-United-Match-Logs-All-Competitions",
  "https://fbref.com/en/squads/7c21e445/2022-2023/matchlogs/all_comps/passing/West-Ham-United-Match-Logs-All-Competitions"
)

all_passing <- list()

for (url in passing_urls) {
  passing <- scrape_passing(url)
  all_passing[[url]] <- passing
  Sys.sleep(5)
}

combined_passing <- bind_rows(all_passing)

view(combined_passing)

# Get the first row of the combined_shooting data frame
new_column_names <- as.character(combined_passing[1, ])

# Set the new column names
colnames(combined_passing) <- new_column_names

# Remove the first row from the combined_shooting data frame
combined_passing <- combined_passing[-1, ] %>% 
  janitor::clean_names() %>% 
  filter(comp == "Premier League") %>% 
  select(date:match_report)

view(combined_passing)

```

```{r possession}

scrape_poss <- function(url) {
  poss_list <- url %>%
    read_html()
  
  poss <- data.frame(
    poss_list %>%
      html_elements("#matchlogs_for") %>%
      html_table()
  ) %>% 
    janitor::clean_names()
  
  return(poss)
}

poss_urls <- c(
  "https://fbref.com/en/squads/7c21e445/2017-2018/matchlogs/all_comps/possession/West-Ham-United-Match-Logs-All-Competitions",
  "https://fbref.com/en/squads/7c21e445/2018-2019/matchlogs/all_comps/possession/West-Ham-United-Match-Logs-All-Competitions",
  "https://fbref.com/en/squads/7c21e445/2019-2020/matchlogs/all_comps/possession/West-Ham-United-Match-Logs-All-Competitions",
  "https://fbref.com/en/squads/7c21e445/2020-2021/matchlogs/all_comps/possession/West-Ham-United-Match-Logs-All-Competitions",
  "https://fbref.com/en/squads/7c21e445/2021-2022/matchlogs/all_comps/possession/West-Ham-United-Match-Logs-All-Competitions",
  "https://fbref.com/en/squads/7c21e445/2022-2023/matchlogs/all_comps/possession/West-Ham-United-Match-Logs-All-Competitions"
)

all_poss <- list()

library(httr)

for (url in poss_urls) {
  response <- GET(url, add_headers(headers))
  poss <- scrape_poss(url)
  all_poss[[url]] <- poss
  Sys.sleep(5)
}

combined_poss <- bind_rows(all_poss)

view(combined_poss)

# Get the first row of the combined_shooting data frame
new_column_names <- as.character(combined_poss[1, ])

# Set the new column names
colnames(combined_poss) <- new_column_names

# Remove the first row from the combined_shooting data frame
combined_poss <- combined_poss[-1, ] %>% 
  janitor::clean_names() %>% 
  filter(comp == "Premier League") %>% 
  select(date:match_report)

view(combined_poss)

```

```{r data_clean}

# Creating a primary key to link the tables

combined_fixtures <- combined_fixtures %>% 
  mutate(year = substr(date, 9, 10),
         matchweek = substr(round, 11, 13),
         game_id = paste(year, matchweek, sep = "_"))

combined_shooting <- combined_shooting %>% 
  mutate(year = substr(date, 9, 10),
         matchweek = substr(round, 11, 13),
         game_id = paste(year, matchweek, sep = "_"))

combined_passing <- combined_passing %>% 
  mutate(year = substr(date, 9, 10),
         matchweek = substr(round, 11, 13),
         game_id = paste(year, matchweek, sep = "_"))

combined_poss <- combined_poss %>% 
  mutate(year = substr(date, 9, 10),
         matchweek = substr(round, 11, 13),
         game_id = paste(year, matchweek, sep = "_"))

# Creating a central "base" table

match_results <- combined_fixtures %>% 
  select(game_id, date, time, round, venue, result, gf, ga, opponent, referee, poss) %>% 
  mutate(gf = as.integer(gf),
         ga = as.integer(ga))

glimpse(match_results)

# Now let's clean up our existing tables so we only keep essential data

combined_fixtures <- combined_fixtures %>% 
  select(game_id, date:opponent, poss, formation) %>% 
  mutate(gf = as.integer(gf),
         ga = as.integer(ga),
         poss = as.double(poss)/100)

glimpse(combined_fixtures)

combined_passing <- combined_passing %>% 
  select(game_id, cmp, att, tot_dist, prg_dist, kp, ppa, crs_pa) %>% 
  rename(pass_cmp = cmp, pass_att = att, cmp_pass_dist = tot_dist, prg_pass_dist = prg_dist, key_passes = kp, pass_pa = ppa, cross_pa = crs_pa) %>% 
  mutate(pass_cmp = as.integer(pass_cmp),
         pass_att = as.integer(pass_att),
         pass_cmp_rate = pass_cmp/pass_att,
         cmp_pass_dist = as.integer(cmp_pass_dist),
         prg_pass_dist = as.integer(prg_pass_dist),
         key_passes = as.integer(key_passes),
         pass_pa = as.integer(pass_pa),
         cross_pa = as.integer(cross_pa))

glimpse(combined_passing)

combined_shooting <- combined_shooting %>% 
  select(game_id, sh, so_t, dist) %>% 
  rename(shots = sh, shots_ot = so_t, avg_shot_dist = dist) %>% 
  mutate(shots = as.integer(shots),
         shots_ot = as.integer(shots_ot),
         shots_ot_rate = round(shots_ot/shots, 2),
         avg_shot_dist = as.integer(avg_shot_dist))

glimpse(combined_shooting)

combined_poss <- combined_poss %>% 
  select(game_id, touches, def_3rd, mid_3rd, att_3rd, att, succ, tot_dist, prg_dist) %>%
  rename(att_carries = att, succ_carries = succ, carry_dist = tot_dist, progressive_carry_dist = prg_dist) %>% 
  mutate(touches = as.integer(touches),
         def_3rd = as.integer(def_3rd),
         mid_3rd = as.integer(mid_3rd),
         att_3rd = as.integer(att_3rd),
         att_carries = as.integer(att_carries),
         succ_carries = as.integer(succ_carries),
         succ_carry_rate = round(succ_carries/att_carries, 2),
         carry_dist = as.integer(carry_dist),
         progressive_carry_dist = as.integer(progressive_carry_dist))

glimpse(combined_poss)

```

```{r eda}

# Total goals for and against in the period

match_results %>% 
  summarise(total_gf = sum(gf), total_ga = sum(ga))

# Some References
source("west_ham_theme.R")
num_shades <- 3
blues <- brewer.pal(num_shades, "Blues")
blue_shades <- colorRampPalette(c("#FFFFFF", "#82C0E5"))(9)
blue_shades <- colorRampPalette(c("#FFFFFF", "#82C0E5"))(9)
red_shades <- colorRampPalette(c("#FF5050", "#FFFFFF"))(9)
contrast_colors <- c("#0B4D92", "#82C0E5", "#FF5050")

# Results in the period

# Calculate the percentage of total games
match_results_summary <- match_results %>%
  group_by(result) %>%
  summarise(number = n()) %>%
  mutate(percentage = number / sum(number) * 100)

# Plot the bar chart with text labels
match_results_plot <-  ggplot(match_results_summary, aes(x = factor(result, levels = c("W", "D", "L")), y = number)) +
  geom_bar(stat = "identity", fill = blues, position = position_dodge(width = 0.5)) +
  geom_text(aes(label = paste0(round(percentage), "%")), vjust = 2, color = west_ham_dark_blue, size = 4) +
  west_ham_theme +
  labs(title = "West Ham results since 2017/18 season",
       subtitle = "Premier League games only",
       x = "Result",
       y = "Number of Matches",
       fill = "Result")

ggsave("images/match_results.png", match_results_plot, width = 16, height = 8)

# Performances by result

result_performances_plot <- match_results %>%
  select(game_id, result, poss) %>%
  left_join(combined_shooting, "game_id") %>%
  left_join(combined_passing, "game_id") %>%
  left_join(combined_poss, "game_id") %>%
  select(game_id, result, poss, shots, shots_ot_rate, avg_shot_dist, pass_cmp, pass_cmp_rate, touches, att_carries, succ_carry_rate, def_3rd, mid_3rd, att_3rd) %>%
  pivot_longer(poss:att_3rd, names_to = "metric", values_to = "value") %>%
  ggplot(aes(x = value, fill = result)) +
  geom_density(alpha = 0.5) +
  facet_wrap(~ metric, scales = "free") +
  scale_fill_manual(values = contrast_colors, labels = c("W" = "Win", "D" = "Draw", "L" = "Loss")) +
  west_ham_theme +
  labs(title = "Statistical Performance by Match Result",
       subtitle = "All West Ham Premier League games since 2017/18 season",
       x = "Value",
       y = "Density",
       fill = "Result")

ggsave("images/result_performances.png", result_performances_plot, width = 16, height = 8)
ggsave("images/cover.png", result_performances_plot, width = 16, height = 5)



# Results by referee

ref_results <- match_results %>% 
  select(result, referee) %>% 
  group_by(referee, result) %>% 
  summarise(count = n()) %>% 
  mutate(total_games = sum(count),
         rate = round(count/total_games*100,2)) %>% 
  filter(rate != 100) %>% 
  ggplot(aes(x = reorder(referee, -total_games), y = rate, fill = result)) +
  scale_fill_manual(values = alpha(contrast_colors, 0.9), labels = c("W" = "Win", "D" = "Draw", "L" = "Loss")) +
  geom_bar(stat = "identity") +
  west_ham_theme +
  labs(title = "Rate of Results for Each Referee",
       subtitle = "West Ham Premier League games since 2017/18",
       x = NULL,
       y = "Rate (%)",
       fill = "Result") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1),
        panel.grid.major = element_blank(),  # Remove major grid lines
        panel.grid.minor = element_blank())  # Remove minor grid lines

ggsave("images/ref_results.png", ref_results, width = 16, height = 8)

# Results by opponent (Wins)

t9_opponents <- match_results %>% 
  select(result, opponent) %>% 
  group_by(opponent, result) %>% 
  summarise(count = n()) %>% 
  mutate(total_games = sum(count),
         rate = round(count/total_games*100, 2)) %>% 
  filter(result == "W") %>%
  arrange(desc(rate)) %>%
  head(9)

t9_opponents_plot <- t9_opponents %>%
  ggplot(aes(x = reorder(opponent, -rate), y = rate, fill = reorder(opponent, rate))) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = blue_shades) +
  west_ham_theme +
  labs(
    title = "Rate of Results for Each Opponent",
    subtitle = "West Ham Premier League games since 2017/18",
    x = NULL,
    y = "Rate (%)",
    fill = "Result",
    color = "Opponent"
  ) +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
  )

ggsave("images/wins.png", t9_opponents_plot, width = 16, height = 8)

# Results by opponent (Losses)

b9_opponents <- match_results %>% 
  select(result, opponent) %>% 
  group_by(opponent, result) %>% 
  summarise(count = n()) %>% 
  mutate(total_games = sum(count),
         rate = round(count/total_games*100, 2)) %>% 
  filter(result == "L") %>%
  arrange(desc(rate)) %>%
  head(9)

b9_opponents_plot <- b9_opponents %>%
  ggplot(aes(x = reorder(opponent, -rate), y = rate, fill = reorder(opponent, -rate))) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = red_shades) +
  west_ham_theme +
  labs(
    title = "Rate of Results for Each Opponent",
    subtitle = "West Ham Premier League games since 2017/18",
    x = NULL,
    y = "Rate (%)",
    fill = "Result",
    color = "Opponent"
  ) +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
  )

ggsave("images/losses.png", b9_opponents_plot, width = 16, height = 8)

```













